<a href="https://colab.research.google.com/github/hanataroty58-del/hana/blob/main/project_term_two_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import sqlite3
conn = sqlite3.connect('/content/download.db')

In [ ]:
#five questions
def run(query) :
    return pd.read_sql_query(query, conn)

In [ ]:
query = """
SELECT
    members.*,
    checkouts.checkout_id,
    checkouts.book_id,
    checkouts.checkout_date
FROM members
JOIN checkouts ON members.member_id = checkouts.member_id;
"""
run(query)

,member_id,first_name,last_name,grade,neighborhood,membership_status,join_date,checkout_id,book_id,checkout_date
0,1047,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,9263,517,2024-10-21
1,1072,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,9340,513,2025-08-24
2,1053,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,9231,523,2024-02-04
3,1032,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,9129,513,2025-06-21
4,1079,Rana,Osman,8.0,Shubra,Active,2024-10-27,9370,511,2025-11-11
...,...,...,...,...,...,...,...,...,...,...
386,1044,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,9232,513,2025-05-26
387,1008,Ziad,Saleh,8.0,Maadi,active,2025-10-28,9084,511,2024-06-27
388,1024,Youssef,Hegazy,8.0,Nasr City,inactive,2024-01-04,9116,519,2025-01-10
389,1076,Dina,Wahba,7.0,Shubra,Active,2025-12-13,9352,501,2025-02-02
390,1044,Sherif,Saleh,7.0,Heliopolis,active,2024-02-19,9246,529,2025-06-25

In [ ]:
query='''SELECT
    members.member_id,
    members.first_name,
    members.last_name,
    COUNT(checkouts.checkout_id) AS total_checkouts
FROM members
JOIN checkouts ON members.member_id = checkouts.member_id
GROUP BY
    members.member_id,
    members.first_name,
    members.last_name'''
run(query)

    member_id first_name last_name  total_checkouts
0        1001      Salma   Ibrahim                1
1        1002      Fares     Saleh                2
2        1003     Bassel    Hegazy                9
3        1005    Youssef     Halim                3
4        1006      Layla   Mansour                1
..        ...        ...       ...              ...
57       1075      Malak     Fahmy                9
58       1076       Dina     Wahba                7
59       1077       Lina    Rashad                6
60       1079       Rana     Osman               10
61       1080     Bassel     Wahba                2

[62 rows x 4 columns]

In [ ]:
query='''SELECT *
FROM books
WHERE author LIKE '%mo%';'''
run(query)

   book_id                   title          author
0      513  Circuits for Beginners    Galal Mounir
1      514   The Robot in Row Nine    Galal Mounir
2      525    Storms and Sailboats   Mahmoud Rafei
3      526   The Clockwork Orchard   Mahmoud Rafei
4      527    Notes from the Delta  Mona Kholoussy
5      528       The Glass Beehive  Mona Kholoussy

In [ ]:
query='''SELECT
    books.title,
    COUNT(checkouts.checkout_id) AS times_checked_out
    FROM
    books
    JOIN
    checkouts ON books.book_id = checkouts.book_id
    GROUP BY
    books.book_id,
    books.title ORDER BY
    times_checked_out DESC
    LIMIT 5;'''
run(query)

                    title  times_checked_out
0         The Silver Kite                 57
1   Fossils and Fireflies                 55
2  Circuits for Beginners                 46
3        Kites Over Cairo                 38
4    Storms and Sailboats                 25

In [ ]:
query='''SELECT
    members.member_id,
    members.first_name,
    members.last_name,
    COUNT(checkouts.checkout_id) AS books_borrowed
FROM
    members
JOIN
    checkouts ON members.member_id = checkouts.member_id
GROUP BY
    members.member_id,
    members.first_name,
    members.last_name
ORDER BY
    books_borrowed DESC
LIMIT 10;'''
run(query)

   member_id first_name last_name  books_borrowed
0       1034        Aya     Wahba              25
1       1044     Sherif     Saleh              21
2       1008       Ziad     Saleh              19
3       1010       Nour     Nabil              18
4       1027    Mostafa     Fouad              18
5       1018      Ahmed    Shafik              17
6       1024    Youssef    Hegazy              17
7       1065       Adam     Fahmy              17
8       1030       Reem     Osman              16
9       1047       Sara    Rashad              16

In [ ]:
query='''SELECT
    members.neighborhood,
    members.member_id,
    checkouts.checkout_id,
    checkouts.checkout_date
FROM
    members
JOIN
    checkouts ON members.member_id = checkouts.member_id
WHERE
    members.neighborhood = 'Zamalek'
ORDER BY
    checkouts.checkout_date DESC
LIMIT 10 OFFSET 10;'''
run(query)

  neighborhood  member_id  checkout_id checkout_date
0      Zamalek       1067         9318    2025-07-23
1      Zamalek       1073         9320    2025-07-19
2      Zamalek       1065         9311    2025-06-26
3      Zamalek       1065         9298    2025-06-18
4      Zamalek       1072         9307    2025-06-10
5      Zamalek       1072         9333    2025-06-03
6      Zamalek       1068         9342    2025-05-28
7      Zamalek       1065         9297    2025-04-14
8      Zamalek       1072         9330    2025-04-11
9      Zamalek       1065         9288    2025-03-20

In [ ]:
#combine task 1
import json
import sqlite3
import pandas as pd

In [ ]:
df_html_checkouts = pd.read_html("download.html")[0]
df_html_checkouts.rename(
    columns={
        "Member ID": "member_id",
        "Book ID": "book_id",
        "Checkout Date": "checkout_date",
    },
    inplace=True,
)

In [ ]:
df_json_books=pd.read_json("/content/download.json")

In [ ]:
conn = sqlite3.connect("download.db")
df_db_checkouts = pd.read_sql_query("SELECT * FROM checkouts", conn)
df_db_books = pd.read_sql_query("SELECT * FROM books", conn)
df_db_members = pd.read_sql_query("SELECT * FROM members", conn)

In [ ]:
df_complete_books = pd.merge(df_db_books, df_json_books, on="book_id")
df_complete_checkouts = pd.concat(
    [df_db_checkouts, df_html_checkouts]
)

In [ ]:
df_master_dataset = (
    df_complete_checkouts.merge(df_db_members, on="member_id")
    .merge(df_complete_books, on="book_id")
)

In [ ]:
df_master_dataset.to_csv("task1_combined_data.csv", index=False)

In [ ]:
# clean task 2
import pandas as pd
df=pd.read_csv('/content/task1_combined_data.csv')

In [ ]:
df

,checkout_id,member_id,book_id,checkout_date,return_date,first_name,last_name,grade,neighborhood,membership_status,join_date,title,author,genre,pages,publication_year,publisher
0,9263.0,1047,517,2024-10-21,2024-11-07,Sara,Rashad,NaN,Heliopolis,Inactive,2024-06-25,Shadows on the Corniche,Hani Nagati,Mystery,338,2015.0,Delta House
1,9340.0,1072,513,2025-08-24,2025-09-01,Seif,Zaki,9.0,Zamalek,Active,2025-10-21,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
2,9231.0,1053,523,2024-02-04,2024-02-16,Adam,Shafik,9.0,Heliopolis,Active,2024-01-03,Footsteps in the Dust,Laila Shokry,Historical,276,2018.0,Oasis Books
3,9129.0,1032,513,2025-06-21,2025-06-29,Nada,Zaki,7.0,Nasr City,Active,2025-10-19,Circuits for Beginners,Galal Mounir,Science,294,2021.0,Oasis Books
4,9370.0,1079,511,2025-11-11,2025-12-03,Rana,Osman,8.0,Shubra,Active,2024-10-27,Winter in Alexandria,Farida Anwar,Historical,117,2016.0,Nile Press
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,NaN,1073,530,2025-07-07,NaN,Yassin,Kamel,7.0,Zamalek,Inactive,2025-08-26,The Sandstone Key,Sara Tantawy,Adventure,208,2012.0,Oasis Books
408,NaN,1003,501,2025-07-08,NaN,Bassel,Hegazy,6.0,Maadi,Active,2025-04-23,The Silver Kite,Amina Darwish,Adventure,128,2017.0,Nile Press
409,NaN,1017,507,2025-07-11,NaN,Adam,Badr,9.0,Maadi,Active,2025-07-12,Fossils and Fireflies,Dalia Serry,Science,160,2024.0,Nile Press
410,NaN,1061,504,2025-07-06,NaN,Ziad,Fahmy,9.0,zamalek,Inactive,2023-04-27,Rooftop Astronomers,Adel Roushdy,Science,319,2009.0,Cairo Young Readers
411,NaN,1041,512,2025-07-06,NaN,Nada,Rashad,7.0,Nasr City,Active,2024-04-02,The Cartographer's Cat,Farida Anwar,Adventure,238,2022.0,Delta House

In [ ]:
df.shape

(412, 17)

In [ ]:
df.dtypes

checkout_id          float64
member_id              int64
book_id                int64
checkout_date         object
return_date           object
first_name            object
last_name             object
grade                float64
neighborhood          object
membership_status     object
join_date             object
title                 object
author                object
genre                 object
pages                  int64
publication_year     float64
publisher             object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   checkout_id        391 non-null    float64
 1   member_id          412 non-null    int64
 2   book_id            412 non-null    int64
 3   checkout_date      412 non-null    object
 4   return_date        326 non-null    object
 5   first_name         412 non-null    object
 6   last_name          412 non-null    object
 7   grade              376 non-null    float64
 8   neighborhood       412 non-null    object
 9   membership_status  412 non-null    object
 10  join_date          406 non-null    object
 11  title              412 non-null    object
 12  author             412 non-null    object
 13  genre              412 non-null    object
 14  pages              412 non-null    int64
 15  publication_year   377 non-null    float64
 16  publisher          412 non-null    object
dtypes: float64(3), int64(3), object(11)
memory usage: 54.8+ KB

In [ ]:
print(df.isna().sum())

checkout_id          21
member_id             0
book_id               0
checkout_date         0
return_date          86
first_name            0
last_name             0
grade                36
neighborhood          0
membership_status     0
join_date             6
title                 0
author                0
genre                 0
pages                 0
publication_year     35
publisher             0
dtype: int64

In [ ]:
df['grade'] = df['grade'].fillna(df['grade'].median())
df['publication_year']=df['publication_year'].fillna(df['publication_year'].mode()[0])
df['return_date'] = df['return_date'].fillna(df['return_date'].mode()[0])
df['checkout_id'] = df['checkout_id'].fillna('UNKNOWN')

In [ ]:
print(df.duplicated().sum())

8

In [ ]:
before=len(df)
print(before)
df= df.drop_duplicates()
after=len(df)
print(after)

412
404

In [ ]:
df['neighborhood'].unique()

array(['Heliopolis', 'Zamalek', 'Nasr City', 'Shubra', 'Maadi ', 'Maadi',
       'zamalek', 'NASR CITY', 'HELIOPOLIS'], dtype=object)

In [ ]:
df['neighborhood'] = df['neighborhood'].str.lower().str.strip()
df['membership_status'] = df['membership_status'].str.lower().str.strip()

/tmp/ipykernel_2390/3189180271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['neighborhood'] = df['neighborhood'].str.lower().str.strip()
/tmp/ipykernel_2390/3189180271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['membership_status'] = df['membership_status'].str.lower().str.strip()

In [ ]:
df['neighborhood'].unique()

array(['heliopolis', 'zamalek', 'nasr city', 'shubra', 'maadi'],
      dtype=object)

In [ ]:
df['membership_status'].unique()

array(['inactive', 'active'], dtype=object)

In [ ]:
df["join_date"] = pd.to_datetime(df["join_date"])
df["publication_year"] = df["publication_year"].astype("Int64")

In [ ]:
df.to_csv('task2_cleaned_data.csv')

In [ ]:
print(df.isna().sum())
print(df.duplicated().sum())

checkout_id          0
member_id            0
book_id              0
checkout_date        0
return_date          0
first_name           0
last_name            0
grade                0
neighborhood         0
membership_status    0
join_date            6
title                0
author               0
genre                0
pages                0
publication_year     0
publisher            0
dtype: int64
0

In [ ]:
#task 3 fairness
df = pd.read_csv("/content/task2_cleaned_data.csv")

checkouts_per_neigh = df["neighborhood"].value_counts()
members_per_neigh = df.drop_duplicates(subset=["neighborhood", "member_id"])[
    "neighborhood"
].value_counts()

fairness_df = pd.DataFrame(
    {
        "Neighborhood": members_per_neigh.index,
        "Unique Members": members_per_neigh.values,
        "Total Checkouts": checkouts_per_neigh[members_per_neigh.index].values,
    }
)

total_members = fairness_df["Unique Members"].sum()
total_checkouts = fairness_df["Total Checkouts"].sum()

fairness_df["Member Share (%)"] = (
    fairness_df["Unique Members"] / total_members * 100
).round(2)
fairness_df["Checkout Share (%)"] = (
    fairness_df["Total Checkouts"] / total_checkouts * 100
).round(2)
fairness_df["Checkouts per Member"] = (
    fairness_df["Total Checkouts"] / fairness_df["Unique Members"]
).round(2)

print(fairness_df.to_string(index=False))

Neighborhood  Unique Members  Total Checkouts  Member Share (%)  Checkout Share (%)  Checkouts per Member
       maadi              20              114             30.77               28.22                  5.70
   nasr city              16              101             24.62               25.00                  6.31
  heliopolis              13               87             20.00               21.53                  6.69
     zamalek              11               68             16.92               16.83                  6.18
      shubra               5               34              7.69                8.42                  6.80